import {
  LayoutDashboard,
  Store,
  Receipt,
  Boxes,
  Carrot,
  UtensilsCrossed,
  Sparkles,
  BarChart3,
  TrendingUp,
  Users,
  ShieldCheck,
  Settings,
  Coffee,
  Cookie,
  ShoppingBag,
  CupSoda,
  GlassWater,
  Flame,
  Pizza,
  Cake,
  Wine,
  Milk,
  Package,
  Clock,
  Heart,
  Tag,
  BookOpen,
  ChefHat,
  Salad,
  Apple,
  Fish,
  Wheat,
} from 'lucide-react';

export const ICON_MAP: Record<string, any> = {
  LayoutDashboard,
  Store,
  Receipt,
  Boxes,
  Carrot,
  UtensilsCrossed,
  Sparkles,
  BarChart3,
  TrendingUp,
  Users,
  ShieldCheck,
  Settings,
  Coffee,
  Cookie,
  ShoppingBag,
  CupSoda,
  GlassWater,
  Flame,
  Pizza,
  Cake,
  Wine,
  Milk,
  Package,
  Clock,
  Heart,
  Tag,
  BookOpen,
  ChefHat,
  Salad,
  Apple,
  Fish,
  Wheat,
};

export const AVAILABLE_ICONS = [
  { key: 'LayoutDashboard', label: 'แดชบอร์ด', icon: LayoutDashboard },
  { key: 'Store',           label: 'หน้าร้าน', icon: Store },
  { key: 'Receipt',         label: 'ใบเสร็จ/บิล', icon: Receipt },
  { key: 'Boxes',           label: 'กล่องสต็อก', icon: Boxes },
  { key: 'Package',         label: 'พัสดุ/ลัง', icon: Package },
  { key: 'Carrot',          label: 'ผัก/วัตถุดิบ', icon: Carrot },
  { key: 'Salad',           label: 'สลัด/อาหารสด', icon: Salad },
  { key: 'Apple',           label: 'ผลไม้', icon: Apple },
  { key: 'Fish',            label: 'ปลา/เนื้อสัตว์', icon: Fish },
  { key: 'ShoppingBag',     label: 'ถุงซื้อของ', icon: ShoppingBag },
  { key: 'UtensilsCrossed', label: 'ช้อนส้อม/อาหาร', icon: UtensilsCrossed },
  { key: 'ChefHat',         label: 'หมวกเชฟ', icon: ChefHat },
  { key: 'Flame',           label: 'ไฟ/อาหารปรุงร้อน', icon: Flame },
  { key: 'Coffee',          label: 'กาแฟ/คาเฟ่', icon: Coffee },
  { key: 'CupSoda',         label: 'น้ำหวาน/โซดา', icon: CupSoda },
  { key: 'GlassWater',      label: 'แก้วน้ำ/เครื่องดื่ม', icon: GlassWater },
  { key: 'Milk',            label: 'นมสด', icon: Milk },
  { key: 'Cookie',          label: 'คุกกี้/ขนม', icon: Cookie },
  { key: 'Cake',            label: 'เค้ก/เบเกอรี่', icon: Cake },
  { key: 'Wheat',           label: 'แป้งสาลี/ข้าว', icon: Wheat },
  { key: 'Pizza',           label: 'พิซซ่า/จานด่วน', icon: Pizza },
  { key: 'Sparkles',        label: 'ดาวประกาย/AI', icon: Sparkles },
  { key: 'BarChart3',       label: 'กราฟแท่ง', icon: BarChart3 },
  { key: 'TrendingUp',      label: 'กราฟขาขึ้น', icon: TrendingUp },
  { key: 'Users',           label: 'ผู้คน/พนักงาน', icon: Users },
  { key: 'ShieldCheck',     label: 'โล่/สิทธิ์', icon: ShieldCheck },
  { key: 'Settings',        label: 'ฟันเฟือง/ตั้งค่า', icon: Settings },
  { key: 'Tag',             label: 'ป้ายราคา', icon: Tag },
  { key: 'Clock',           label: 'นาฬิกา/เวลา', icon: Clock },
  { key: 'BookOpen',        label: 'สมุดสูตร', icon: BookOpen },
];
